version: '3.1'

services:
    backend:
      build: ./backend
      environment:
        - PORT=5000  ## I am using environment variables here to run the server, not exposing the port since we are using network-bridge to communicate.
        ## we can directly use container names here because of bridge, docker is completely similar to my system, need to install dependcies, mount volume for permanent storage and run.
      restart: unless-stopped
      networks:
        - web-network

    frontend:
      build: ./frontend
      environment:
        - PORT=3000
      networks:
        - web-network
    nginx:
      image: nginx
      container_name: webserver
      restart: unless-stopped
      depends_on:
        - backend
        - frontend
      ports:
        - 8080:8080
      volumes:
        - ./nginx/local.conf:/etc/nginx/nginx.conf
      networks:
        - web-network

networks:
  web-network:
    driver: bridge